name       : fs-uae-dev
version    : 2.9.7
release    : 4
source     :
    - https://fs-uae.net/devel/2.9.7dev2/fs-uae-2.9.7dev2.tar.gz : 72cc085e6c822eb843e4f85506e1be070755e3c89a546820e94b9ba2936a03a9
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Multi-platform Amiga emulator based on WinUAE (Development Version)
description: |
    FS-UAE integrates the most accurate Amiga emulation code available from WinUAE. FS-UAE emulates A500, A500+, A600, A1200, A1000, A3000 and A4000 models, but you can tweak the hardware configuration and create customized Amigas.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpeg2)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(xtst)
setup      : |
    %configure --with-glew
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
