name       : fs-uae-dev
version    : 3.0.5
release    : 12
source     :
    - https://fs-uae.net/stable/3.0.5/fs-uae-3.0.5.tar.gz : f26ec42e03cf1a7b53b6ce0d9845aa45bbf472089b5ec046b3eb784ec6859fe3
license    : GPL-2.0-or-later
component  : games.emulator
homepage   : https://fs-uae.net/
summary    : Multi-platform Amiga emulator based on WinUAE (Development Version)
description: |
    FS-UAE integrates the most accurate Amiga emulation code available from WinUAE. FS-UAE emulates A500, A500+, A600, A1200, A1000, A3000 and A4000 models, but you can tweak the hardware configuration and create customized Amigas.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpeg2)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(xtst)
setup      : |
    %configure --with-glew
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc/
check      : |
    %make check
