name       : fs-uae-dev
version    : 2.7.6
release    : 1
source     :
    - http://fs-uae.net/fs-uae/devel/2.7.6dev/fs-uae-2.7.6dev.tar.gz : 2a8c9d010e739f4e42c11557b86bf0b30ee3ee9f2bf2289d70799e20ea2be630
license    : GPL-2.0
summary    : Multi-platform Amiga emulator based on WinUAE (Development Version).
description: FS-UAE integrates the most accurate Amiga emulation code available from WinUAE. FS-UAE emulates A500, A500+, A600, A1200, A1000, A3000 and A4000 models, but you can tweak the hardware configuration and create customized Amigas.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(openal)   
    - pkgconfig(glew)
    - pkgconfig(gl)
    - pkgconfig(xi)
    - pkgconfig(libmpeg2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
